version: '2'

# TODO a thrid service with webhooks support
services:
  etcd:
    image: quay.io/coreos/etcd:v3.0.14
    ports:
      - '2379:2379'
      - '2380:2380'

  dkron:
    build:
      context: '.'
      dockerfile: './dkron.Dockerfile'
      args:
        DKRON_VERSION: '0.9.1'
    ports:
      - '8080:8080'
    links:
      - etcd
    command: 'agent -server -backend=etcd -backend-machine=etcd:2379'
