version: '2'

services:

  ## Monitor logs

  elasticsearch:
    image: elasticsearch:2.3.3
    ports:
      - 9200:9200

  kibana:
    image: kibana:4.5.1
    ports:
      - 5601:5601
    links:
      - elasticsearch

  filebeat:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    links:
      - elasticsearch
    command: filebeat.sh -e -c /app/filebeat.yml

  ## Monitor metrics

  influx:
    image: 'influxdb:1.0.2-alpine'
    # TODO challenge environment variables and ports
    ports:
      - '8083:8083'
      - '8086:8086'
      - '4444:4444/udp'
    expose:
      - 8090
      - 8099
      - 4444
    environment:
      - 'INFLUXDB_PRE_CREATE_DB=metrics'
      - 'INFLUXDB_FORCE_HOSTNAME=auto'
      - 'INFLUXDB_UDP_ENABLED=true'
      - 'INFLUXDB_UDP_DATABASE=metrics'
      - 'INFLUXDB_UDP_BIND_ADDRESS=:4444'

  kapacitor:
    build: ./kapacitor
    stdin_open: true
    tty: true
    volumes:
      - ./kapacitor:/app
    links:
      - influx
    command: sleep
