version: '2'

services:

  elasticsearch:
    image: elasticsearch:2.3.3
    ports:
      - 9200:9200

  kibana:
    image: kibana:4.5.1
    ports:
      - 5601:5601
    links:
      - elasticsearch

  filebeat:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    links:
      - elasticsearch
    command: filebeat.sh -c /app/filebeat.yml
