version: '2'

services:

  kong-database:
    image: 'postgres:9.6.1-alpine'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=kong'
      - 'POSTGRES_DB=kong'

  kong:
    image: 'kong:0.9.7'
    volumes:
      - ./replicate-plugin:/usr/local/kong/plugins/replicate-plugin
    environment:
      - 'KONG_DATABASE=postgres'
      - 'KONG_PG_HOST=kong-database'
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '7946:7946'
      - '7946:7946/udp'
    links:
      - 'kong-database:kong-database'
